### PR TITLE
Fixed and tested issue #44

### PR DESCRIPTION
**Pull request by SridharJagannathan**
Fix and test issue #44

### CODE REVIEW

**Comment by jefferis** [comment]
hi @SridharJagannathan, thanks for this. It looks like the travis encoding of secure environment variables didn't work.

1. I guess I need to figure out why that failed. I think it was because of special characters in the server path.
2. it would be great if you could make the tests *conditional* on having a valid connection. See https://github.com/jefferis/rcatmaid/blob/master/tests/testthat/test-connections.R#L10 and https://github.com/jefferis/rcatmaid/blob/master/tests/testthat/test-connections.R#L30 for how to do this. (Wrap in try then use `testthat::skip` if necessary.

**Comment by jefferis** [comment]
I've updated the environment variables (by putting them in quotes), but it's possible that it doesn't like variables of the form `catmaid.x` and we need to change to `catmaid_x` as you found on your linux box. Take a look at the job log later.

**Comment by SridharJagannathan** [comment]
Thank you @jefferis, I have made them optional and the build seems to be passing now.
@fmlove Can you please review and close the issue #44

**Comment by fmlove** [comment]
Looks good to me.  I added a small tweak to the parameter descriptions so that they're up-to-date and make sense in the context of the new examples.

**Pull request merged**
