### PR TITLE
 Add functions to read googlesheets on team drive

### PR DESCRIPTION
**Pull request by jefferis**

### CODE REVIEW

**Comment by jefferis** [comment]
@fmlove, I think we should maybe move this repo to flyconnectome since we will use it now that you've left the group :-(. I guess since there is already a fork there, that would mostly mean updating the URLs in the package.

**Comment by fmlove** [comment]
I'm happy for it to be moved to flyconnectome, as long as I can keep access to it.  I haven't had much time recently, but I'd like to stay involved in the development.

**Comment by jefferis** [comment]
> I'm happy for it to be moved to flyconnectome, as long as I can keep access to it. I haven't had much time recently, but I'd like to stay involved in the development.

That would be great! You'd still be the official maintainer and be a repo admin. Do you want to go ahead?

**Comment by fmlove** [comment]
Sure.  I'll accept this pull request as soon as the Travis build finishes, and then I can transfer the repo over.

**Comment by jefferis** [comment]
I've added the remote for nat.flybrains that looks like it was at the origin of the travis failure – was already broken AFAICS, although I didn't try to track down since when.

**Pull request merged**
